# Generated by Django 2.2 on 2021-05-01 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20210501_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='is_moderated',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='промодерировано'),
        ),
    ]
